In [1]:
import uproot
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import ROOT


%matplotlib inline
%jsroot on

Welcome to JupyROOT 6.22/01


In [2]:
positron_features_data = pd.read_pickle("new_combined_data_positron_features_82.pkl")
positron_features_data

beamEnergy  trueBeamEnergy  \
71746         20.0       20.000000   
258314       100.0       99.830002   
18871         20.0       20.000000   
127926        50.0       49.990002   
79205         20.0       20.000000   
...            ...             ...   
196232       100.0       99.830002   
225431       100.0       99.830002   
428402       300.0      287.179993   
419756       300.0      287.179993   
362624       200.0      197.320007   

                                              features_82  
71746   [19.620185911655426, 42.86726224422455, 81.833...  
258314  [19.80180013179779, 111.67931747436523, 307.72...  
18871   [31.33267619460821, 80.87321257591248, 191.973...  
127926  [14.808391571044922, 67.0694465637207, 123.298...  
79205   [7.694568514823914, 43.950953245162964, 61.200...  
...                                                   ...  
196232  [21.99822837114334, 96.83178961277008, 274.127...  
225431  [24.746097564697266, 70.07785701751709, 225.84...  
428402  [9.173689126968384, 29.458719730377197, 129.79...  
419756  [35.232404470443726, 100.07887268066406, 326.3...  
362624  [40.80586302280426, 112.69513101875782, 391.81...  

[469791 rows x 3 columns]

In [10]:
positron_features_data.loc[positron_features_data.beamEnergy==20]

beamEnergy  trueBeamEnergy  \
71746        20.0            20.0   
18871        20.0            20.0   
79205        20.0            20.0   
26029        20.0            20.0   
57640        20.0            20.0   
...           ...             ...   
75402        20.0            20.0   
17393        20.0            20.0   
80838        20.0            20.0   
67754        20.0            20.0   
34447        20.0            20.0   

                                             features_82  
71746  [19.620185911655426, 42.86726224422455, 81.833...  
18871  [31.33267619460821, 80.87321257591248, 191.973...  
79205  [7.694568514823914, 43.950953245162964, 61.200...  
26029  [31.60727310180664, 67.72493088245392, 108.428...  
57640  [10.801315903663635, 46.29008865356445, 117.90...  
...                                                  ...  
75402  [28.871707677841187, 95.48757529258728, 168.71...  
17393  [33.01550483703613, 112.52316379547119, 198.18...  
80838  [18.419427275657654, 34.41584777832031, 94.847...  
67754  [30.308873653411865, 99.90964341163635, 193.00...  
34447  [35.73287099599838, 106.57755720615387, 148.18...  

[99006 rows x 3 columns]

In [13]:
lay_ecal_energy_20 = np.stack(positron_features_data.loc[positron_features_data.beamEnergy==20].features_82.values)
print(lay_ecal_energy.shape)
lay_ecal_energy_20

(99006, 82)


array([[1.96201859e+01, 4.28672622e+01, 8.18331010e+01, ...,
        2.03900568e+03, 2.00145102e+00, 0.00000000e+00],
       [3.13326762e+01, 8.08732126e+01, 1.91973770e+02, ...,
        1.76719038e+03, 9.41285264e+00, 0.00000000e+00],
       [7.69456851e+00, 4.39509532e+01, 6.12006241e+01, ...,
        1.97780686e+03, 1.29601800e+00, 0.00000000e+00],
       ...,
       [1.84194273e+01, 3.44158478e+01, 9.48475809e+01, ...,
        2.06535422e+03, 0.00000000e+00, 0.00000000e+00],
       [3.03088737e+01, 9.99096434e+01, 1.93008202e+02, ...,
        2.14829308e+03, 0.00000000e+00, 0.00000000e+00],
       [3.57328710e+01, 1.06577557e+02, 1.48185199e+02, ...,
        1.99258397e+03, 0.00000000e+00, 0.00000000e+00]])

In [16]:
lay_ecal_energy[27,0]

31.33267619460821

In [54]:
c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Positron (20Gev); Layer number; Deposited Energy (MIPS)",56, 1, 29, 50, 0, 600)

for n in range(28):
    for i in range(lay_ecal_energy[:,0].size):
        H.Fill(n+1, lay_ecal_energy_20[i,n])
    
H.Draw("COLZ")
c1.Draw()

Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [42]:
lay_ecal_energy_50 = np.stack(positron_features_data.loc[positron_features_data.beamEnergy==50].features_82.values)
print(lay_ecal_energy.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Positron (50Gev); Layer number; Deposited Energy (MIPS)",56, 1, 29, 50, 0, 1400)

for n in range(28):
    for i in range(lay_ecal_energy_50[:,0].size):
        H.Fill(n+1, lay_ecal_energy_50[i,n])
    
H.Draw("COLZ")
c1.Draw()

(99006, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [60]:
lay_ecal_energy_100 = np.stack(positron_features_data.loc[positron_features_data.beamEnergy==100].features_82.values)
print(lay_ecal_energy.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Positron (100Gev); Layer number; Deposited Energy (MIPS)",56, 1, 29, 50, 0, 2000)

for n in range(28):
    for i in range(lay_ecal_energy_100[:,0].size):
        H.Fill(n+1, lay_ecal_energy_100[i,n])
    
H.Draw("COLZ")
c1.Draw()

(99006, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [62]:
lay_ecal_energy_200 = np.stack(positron_features_data.loc[positron_features_data.beamEnergy==200].features_82.values)
print(lay_ecal_energy.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Positron (200Gev); Layer number; Deposited Energy (MIPS)",56, 1, 29, 50, 0, 3300)

for n in range(28):
    for i in range(lay_ecal_energy_200[:,0].size):
        H.Fill(n+1, lay_ecal_energy_200[i,n])
    
H.Draw("COLZ")
c1.Draw()

(99006, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [66]:
lay_ecal_energy_300 = np.stack(positron_features_data.loc[positron_features_data.beamEnergy==300].features_82.values)
print(lay_ecal_energy_300.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Positron (300Gev); Layer number; Deposited Energy (MIPS)",56, 1, 29, 50, 0, 4300)

for n in range(28):
    for i in range(lay_ecal_energy_300[:,0].size):
        H.Fill(n+1, lay_ecal_energy_300[i,n])
    
H.Draw("COLZ")
c1.Draw()

(79303, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [49]:
x = np.array([[1000,1000,0.01], [2000,1000,20], [1000,3000,0.01]])
y = np.array([[300], [400], [500]])
print(x)
print(y)
print(np.matmul(x.T,y))

[[1.e+03 1.e+03 1.e-02]
 [2.e+03 1.e+03 2.e+01]
 [1.e+03 3.e+03 1.e-02]]
[[300]
 [400]
 [500]]
[[1600000.]
 [2200000.]
 [   8008.]]


In [50]:
xt_x = np.matmul(x.T,x)
xt_x_inv = np.linalg.pinv(xt_x)
print(xt_x)
print(xt_x_inv)
print(np.matmul(xt_x_inv, xt_x))

[[6.000000e+06 6.000000e+06 4.002000e+04]
 [6.000000e+06 1.100000e+07 2.004000e+04]
 [4.002000e+04 2.004000e+04 4.000002e+02]]
[[ 2.50400588e-06 -1.00075075e-06 -2.00388076e-04]
 [-1.00075075e-06  5.00000000e-07  7.50750751e-05]
 [-2.00388076e-04  7.50750751e-05  1.87875563e-02]]
[[ 1.00000000e+00 -9.50845305e-16  7.11669019e-18]
 [ 4.32000356e-16  1.00000000e+00 -2.51499746e-19]
 [ 1.71446191e-13  3.05810932e-13  1.00000000e+00]]


In [51]:
print(np.matmul(xt_x_inv, np.matmul(x.T,y)))

[[ 0.20005005]
 [ 0.1       ]
 [-5.00500501]]


In [2]:
pion_features_data = pd.read_pickle("new_combined_data_pion_features_82.pkl")
pion_features_data

beamEnergy  trueBeamEnergy  \
112520        50.0       49.469673   
429496       300.0      298.298615   
127960        50.0       49.489178   
232587       100.0      100.135193   
483258       300.0      297.879120   
...            ...             ...   
72800         20.0       19.744566   
423144       300.0      297.396423   
392770       200.0      198.109177   
177568        50.0       49.803936   
158889        50.0       50.244495   

                                              features_82  
112520  [2.2882659435272217, 1.9650121927261353, 4.975...  
429496  [0.9531618356704712, 0.8870372772216797, 0.524...  
127960  [1.039785623550415, 1.201719880104065, 71.1739...  
232587  [1.9905580282211304, 6.891543924808502, 6.9337...  
483258  [0.7827611565589905, 1.615274727344513, 0.7945...  
...                                                   ...  
72800   [1.0563750267028809, 1.3372515439987183, 1.368...  
423144  [1.0360097885131836, 0.9656434059143066, 0.842...  
392770  [1.3412532806396484, 0.919788658618927, 0.8255...  
177568  [0.9540113806724548, 2.3491640090942383, 2.188...  
158889  [1.2259968519210815, 1.4584753513336182, 1.331...  

[497521 rows x 3 columns]

In [3]:
lay_energy_20 = np.stack(pion_features_data.loc[pion_features_data.beamEnergy==20].features_82.values)
print(lay_energy_20.shape)
lay_energy_20

(99504, 82)


array([[7.31565065e+01, 2.50385178e+01, 3.43532441e+01, ...,
        5.30534432e+02, 3.55091167e+01, 5.72108383e+01],
       [6.70347118e+00, 1.65925884e+00, 8.00638139e-01, ...,
        4.13805710e+01, 1.48320262e+01, 5.04062462e+01],
       [7.43800223e-01, 9.20403719e-01, 8.39225173e-01, ...,
        3.56734164e+01, 2.03719172e+02, 6.36676483e+01],
       ...,
       [1.46537960e+00, 1.70883238e+00, 1.26747286e+00, ...,
        1.02845467e+03, 5.52961308e+01, 0.00000000e+00],
       [2.35351968e+00, 3.36535889e+01, 2.03047019e+00, ...,
        3.12397946e+02, 1.70754522e+02, 0.00000000e+00],
       [1.05637503e+00, 1.33725154e+00, 1.36892140e+00, ...,
        4.31454151e+01, 4.08447321e+02, 0.00000000e+00]])

In [43]:
c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Pion (20Gev); Layer number; Deposited Energy (MIPS)",79, 1, 79, 500, 0, 1400)

for n in range(79):
    for i in range(lay_energy_20[:,0].size):
        H.Fill(n+1, lay_energy_20[i,n])
    
H.Draw("COLZ")
ROOT.gPad.SetLogy()
c1.Draw()

Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [48]:
lay_ecal_energy_50 = np.stack(pion_features_data.loc[pion_features_data.beamEnergy==50].features_82.values)
print(lay_ecal_energy_50.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Pion (50Gev); Layer number; Deposited Energy (MIPS)",79, 1, 79, 500, 0, 1400)

for n in range(79):
    for i in range(lay_ecal_energy_50[:,0].size):
        H.Fill(n+1, lay_ecal_energy_50[i,n])
    
H.Draw("COLZ")
ROOT.gPad.SetLogy()
c1.Draw()

(99504, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [45]:
lay_ecal_energy_100 = np.stack(pion_features_data.loc[pion_features_data.beamEnergy==100].features_82.values)
print(lay_ecal_energy_100.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Pion (100Gev); Layer number; Deposited Energy (MIPS)",79, 1, 79, 500, 0, 1800)

for n in range(79):
    for i in range(lay_ecal_energy_100[:,0].size):
        H.Fill(n+1, lay_ecal_energy_100[i,n])
    
H.Draw("COLZ")
ROOT.gPad.SetLogy()
c1.Draw()

(99504, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [46]:
lay_ecal_energy_200 = np.stack(pion_features_data.loc[pion_features_data.beamEnergy==200].features_82.values)
print(lay_ecal_energy_200.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Pion (200Gev); Layer number; Deposited Energy (MIPS)",79, 1, 79, 500, 0, 2200)

for n in range(79):
    for i in range(lay_ecal_energy_200[:,0].size):
        H.Fill(n+1, lay_ecal_energy_200[i,n])
    
H.Draw("COLZ")
ROOT.gPad.SetLogy()
c1.Draw()

(99504, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).


In [47]:
lay_ecal_energy_300 = np.stack(pion_features_data.loc[pion_features_data.beamEnergy==200].features_82.values)
print(lay_ecal_energy_300.shape)


c1 = ROOT.TCanvas()
H = ROOT.TH2D("h","Pion (300Gev); Layer number; Deposited Energy (MIPS)",79, 1, 79, 500, 0, 2200)

for n in range(79):
    for i in range(lay_ecal_energy_300[:,0].size):
        H.Fill(n+1, lay_ecal_energy_300[i,n])
    
H.Draw("COLZ")
ROOT.gPad.SetLogy()
c1.Draw()

(99504, 82)


Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).
